apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ printf "%s-%s" .Release.Name  "secrets" }}
    release: {{ .Release.Name }}
  name: {{ printf "%s-%s" .Release.Name  "secrets" }}
data:
  rsab64: {{ .Values.rsab64 }}